/**
 * Tool-Specific Feedback Templates
 * Provides specialized feedback templates for different tool categories and types
 */

import { FeedbackTemplate } from '@/types/feedback';

// ============================================================================
// JSON Processing Suite Templates
// ============================================================================

export const jsonFormatterTemplate: FeedbackTemplate = {
  id: 'json-formatter-feedback',
  name: 'JSON Formatter Feedback',
  type: 'satisfaction',
  title: 'How was your JSON formatting experience?',
  description: 'Help us improve our JSON formatter tool',
  questions: [
    {
      id: 'overallRating',
      type: 'rating',
      text: 'How satisfied are you with the JSON formatter?',
      required: true,
      validation: { max: 5 },
      order: 1,
    },
    {
      id: 'formattingAccuracy',
      type: 'rating',
      text: 'How accurate was the formatting?',
      required: true,
      validation: { max: 5 },
      order: 2,
    },
    {
      id: 'performance',
      type: 'rating',
      text: 'How was the performance with your data size?',
      required: true,
      validation: { max: 5 },
      order: 3,
    },
    {
      id: 'featuresUsed',
      type: 'multiple_choice',
      text: 'Which features did you use? (Select all that apply)',
      options: [
        { value: 'basic_formatting', label: 'Basic formatting' },
        { value: 'custom_indentation', label: 'Custom indentation' },
        { value: 'sort_keys', label: 'Sort keys' },
        { value: 'minify', label: 'Minify JSON' },
        { value: 'validation', label: 'JSON validation' },
        { value: 'color_syntax', label: 'Syntax highlighting' },
      ],
      required: false,
      order: 4,
    },
    {
      id: 'dataSize',
      type: 'choice',
      text: 'What was the approximate size of your JSON data?',
      options: [
        { value: 'small', label: 'Small (< 1KB)' },
        { value: 'medium', label: 'Medium (1KB - 100KB)' },
        { value: 'large', label: 'Large (100KB - 1MB)' },
        { value: 'very_large', label: 'Very large (> 1MB)' },
      ],
      required: false,
      order: 5,
    },
    {
      id: 'improvements',
      type: 'textarea',
      text: 'What improvements would you like to see in the JSON formatter?',
      required: false,
      validation: { maxLength: 500 },
      order: 6,
    },
  ],
  layout: {
    type: 'single_page',
    columns: 1,
    sections: [
      {
        id: 'ratings',
        title: 'Rate Your Experience',
        questions: ['overallRating', 'formattingAccuracy', 'performance'],
        order: 1,
      },
      {
        id: 'usage',
        title: 'Usage Information',
        questions: ['featuresUsed', 'dataSize'],
        order: 2,
      },
      {
        id: 'feedback',
        title: 'Your Feedback',
        questions: ['improvements'],
        order: 3,
      },
    ],
    progressIndicator: true,
    navigation: {
      showPrevious: false,
      showNext: false,
      showSubmit: true,
      showCancel: true,
      submitLabel: 'Submit Feedback',
    },
  },
  styling: {
    theme: 'auto',
    colors: {
      primary: '#3B82F6',
      secondary: '#6B7280',
      accent: '#10B981',
      background: '#FFFFFF',
      surface: '#F9FAFB',
      text: '#111827',
      error: '#EF4444',
      warning: '#F59E0B',
      success: '#10B981',
    },
    typography: {
      fontFamily: 'Inter, system-ui, sans-serif',
      fontSize: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
      },
      fontWeight: {
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
      },
      lineHeight: 1.5,
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '1rem',
      lg: '1.5rem',
      xl: '2rem',
      '2xl': '3rem',
    },
    animations: {
      duration: 200,
      easing: 'ease-in-out',
      enabled: true,
    },
  },
  localization: {
    title: 'How was your JSON formatting experience?',
    description: 'Help us improve our JSON formatter tool',
    questions: {
      overallRating: 'How satisfied are you with the JSON formatter?',
      formattingAccuracy: 'How accurate was the formatting?',
      performance: 'How was the performance with your data size?',
      featuresUsed: 'Which features did you use? (Select all that apply)',
      dataSize: 'What was the approximate size of your JSON data?',
      improvements: 'What improvements would you like to see in the JSON formatter?',
    },
    buttons: {
      previous: 'Previous',
      next: 'Next',
      submit: 'Submit Feedback',
      cancel: 'Cancel',
      skip: 'Skip',
    },
    validation: {
      required: 'This field is required',
      invalid: 'Please enter a valid value',
      minLength: 'Minimum length is {min} characters',
      maxLength: 'Maximum length is {max} characters',
    },
  },
};

export const jsonValidatorTemplate: FeedbackTemplate = {
  id: 'json-validator-feedback',
  name: 'JSON Validator Feedback',
  type: 'bug_report',
  title: 'JSON Validator Issue Report',
  description: 'Report issues or provide feedback about our JSON validator',
  questions: [
    {
      id: 'issueType',
      type: 'choice',
      text: 'What type of issue are you reporting?',
      required: true,
      options: [
        { value: 'false_positive', label: 'False positive (valid JSON flagged as invalid)' },
        { value: 'false_negative', label: 'False negative (invalid JSON passed as valid)' },
        { value: 'performance', label: 'Performance issue' },
        { value: 'feature_request', label: 'Feature request' },
        { value: 'other', label: 'Other issue' },
      ],
      order: 1,
    },
    {
      id: 'severity',
      type: 'choice',
      text: 'How severe is this issue?',
      required: true,
      options: [
        { value: 'low', label: 'Low - Minor inconvenience' },
        { value: 'medium', label: 'Medium - Affects usability' },
        { value: 'high', label: 'High - Blocks important work' },
        { value: 'critical', label: 'Critical - Completely unusable' },
      ],
      order: 2,
    },
    {
      id: 'jsonSample',
      type: 'textarea',
      text: 'Please provide a sample JSON that demonstrates the issue (remove any sensitive data)',
      required: true,
      validation: { minLength: 10, maxLength: 5000 },
      order: 3,
    },
    {
      id: 'expectedBehavior',
      type: 'textarea',
      text: 'What did you expect to happen?',
      required: true,
      validation: { minLength: 5, maxLength: 1000 },
      order: 4,
    },
    {
      id: 'actualBehavior',
      type: 'textarea',
      text: 'What actually happened?',
      required: true,
      validation: { minLength: 5, maxLength: 1000 },
      order: 5,
    },
    {
      id: 'reproductionSteps',
      type: 'textarea',
      text: 'Steps to reproduce the issue',
      required: false,
      validation: { maxLength: 1000 },
      order: 6,
    },
  ],
  layout: {
    type: 'single_page',
    columns: 1,
    sections: [
      {
        id: 'issue_details',
        title: 'Issue Details',
        questions: ['issueType', 'severity'],
        order: 1,
      },
      {
        id: 'demonstration',
        title: 'Issue Demonstration',
        questions: ['jsonSample', 'expectedBehavior', 'actualBehavior'],
        order: 2,
      },
      {
        id: 'reproduction',
        title: 'Reproduction Steps',
        questions: ['reproductionSteps'],
        order: 3,
      },
    ],
    progressIndicator: true,
    navigation: {
      showPrevious: false,
      showNext: false,
      showSubmit: true,
      showCancel: true,
      submitLabel: 'Report Issue',
    },
  },
  styling: {
    theme: 'auto',
    colors: {
      primary: '#EF4444',
      secondary: '#6B7280',
      accent: '#3B82F6',
      background: '#FFFFFF',
      surface: '#FEF2F2',
      text: '#111827',
      error: '#EF4444',
      warning: '#F59E0B',
      success: '#10B981',
    },
    typography: {
      fontFamily: 'Inter, system-ui, sans-serif',
      fontSize: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
      },
      fontWeight: {
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
      },
      lineHeight: 1.5,
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '1rem',
      lg: '1.5rem',
      xl: '2rem',
      '2xl': '3rem',
    },
    animations: {
      duration: 200,
      easing: 'ease-in-out',
      enabled: true,
    },
  },
  localization: {
    title: 'JSON Validator Issue Report',
    description: 'Report issues or provide feedback about our JSON validator',
    questions: {
      issueType: 'What type of issue are you reporting?',
      severity: 'How severe is this issue?',
      jsonSample: 'Please provide a sample JSON that demonstrates the issue',
      expectedBehavior: 'What did you expect to happen?',
      actualBehavior: 'What actually happened?',
      reproductionSteps: 'Steps to reproduce the issue',
    },
    buttons: {
      previous: 'Previous',
      next: 'Next',
      submit: 'Report Issue',
      cancel: 'Cancel',
      skip: 'Skip',
    },
    validation: {
      required: 'This field is required',
      invalid: 'Please enter a valid value',
      minLength: 'Minimum length is {min} characters',
      maxLength: 'Maximum length is {max} characters',
    },
  },
};

// ============================================================================
// Code Processing Suite Templates
// ============================================================================

export const codeFormatterTemplate: FeedbackTemplate = {
  id: 'code-formatter-feedback',
  name: 'Code Formatter Feedback',
  type: 'satisfaction',
  title: 'Code Formatter Experience',
  description: 'Help us improve our code formatting tools',
  questions: [
    {
      id: 'languageUsed',
      type: 'choice',
      text: 'Which programming language did you format?',
      required: true,
      options: [
        { value: 'javascript', label: 'JavaScript' },
        { value: 'typescript', label: 'TypeScript' },
        { value: 'python', label: 'Python' },
        { value: 'java', label: 'Java' },
        { value: 'csharp', label: 'C#' },
        { value: 'cpp', label: 'C++' },
        { value: 'go', label: 'Go' },
        { value: 'rust', label: 'Rust' },
        { value: 'other', label: 'Other' },
      ],
      order: 1,
    },
    {
      id: 'formattingQuality',
      type: 'rating',
      text: 'How would you rate the formatting quality?',
      required: true,
      validation: { max: 5 },
      order: 2,
    },
    {
      id: 'customizationOptions',
      type: 'rating',
      text: 'How satisfied are you with the customization options?',
      required: true,
      validation: { max: 5 },
      order: 3,
    },
    {
      id: 'performance',
      type: 'rating',
      text: 'How was the performance with your code size?',
      required: true,
      validation: { max: 5 },
      order: 4,
    },
    {
      id: 'codeComplexity',
      type: 'choice',
      text: 'How complex was the code you formatted?',
      options: [
        { value: 'simple', label: 'Simple (basic syntax)' },
        { value: 'moderate', label: 'Moderate (functions, classes)' },
        { value: 'complex', label: 'Complex (advanced features)' },
        { value: 'very_complex', label: 'Very complex (large codebase)' },
      ],
      required: false,
      order: 5,
    },
    {
      id: 'suggestions',
      type: 'textarea',
      text: 'What formatting options or improvements would you like to see?',
      required: false,
      validation: { maxLength: 500 },
      order: 6,
    },
  ],
  layout: {
    type: 'single_page',
    columns: 1,
    sections: [
      {
        id: 'language_info',
        title: 'Language Information',
        questions: ['languageUsed'],
        order: 1,
      },
      {
        id: 'ratings',
        title: 'Rate Your Experience',
        questions: ['formattingQuality', 'customizationOptions', 'performance'],
        order: 2,
      },
      {
        id: 'complexity',
        title: 'Code Complexity',
        questions: ['codeComplexity'],
        order: 3,
      },
      {
        id: 'suggestions',
        title: 'Your Suggestions',
        questions: ['suggestions'],
        order: 4,
      },
    ],
    progressIndicator: true,
    navigation: {
      showPrevious: false,
      showNext: false,
      showSubmit: true,
      showCancel: true,
      submitLabel: 'Submit Feedback',
    },
  },
  styling: {
    theme: 'auto',
    colors: {
      primary: '#3B82F6',
      secondary: '#6B7280',
      accent: '#10B981',
      background: '#FFFFFF',
      surface: '#F9FAFB',
      text: '#111827',
      error: '#EF4444',
      warning: '#F59E0B',
      success: '#10B981',
    },
    typography: {
      fontFamily: 'Inter, system-ui, sans-serif',
      fontSize: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
      },
      fontWeight: {
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
      },
      lineHeight: 1.5,
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '1rem',
      lg: '1.5rem',
      xl: '2rem',
      '2xl': '3rem',
    },
    animations: {
      duration: 200,
      easing: 'ease-in-out',
      enabled: true,
    },
  },
  localization: {
    title: 'Code Formatter Experience',
    description: 'Help us improve our code formatting tools',
    questions: {
      languageUsed: 'Which programming language did you format?',
      formattingQuality: 'How would you rate the formatting quality?',
      customizationOptions: 'How satisfied are you with the customization options?',
      performance: 'How was the performance with your code size?',
      codeComplexity: 'How complex was the code you formatted?',
      suggestions: 'What formatting options or improvements would you like to see?',
    },
    buttons: {
      previous: 'Previous',
      next: 'Next',
      submit: 'Submit Feedback',
      cancel: 'Cancel',
      skip: 'Skip',
    },
    validation: {
      required: 'This field is required',
      invalid: 'Please enter a valid value',
      minLength: 'Minimum length is {min} characters',
      maxLength: 'Maximum length is {max} characters',
    },
  },
};

// ============================================================================
// File Processing Suite Templates
// ============================================================================

export const fileConverterTemplate: FeedbackTemplate = {
  id: 'file-converter-feedback',
  name: 'File Converter Feedback',
  type: 'usability',
  title: 'File Conversion Experience',
  description: 'Tell us about your file conversion experience',
  questions: [
    {
      id: 'conversionType',
      type: 'choice',
      text: 'What type of conversion did you perform?',
      required: true,
      options: [
        { value: 'json_to_csv', label: 'JSON to CSV' },
        { value: 'csv_to_json', label: 'CSV to JSON' },
        { value: 'json_to_xml', label: 'JSON to XML' },
        { value: 'xml_to_json', label: 'XML to JSON' },
        { value: 'pdf_conversion', label: 'PDF conversion' },
        { value: 'image_conversion', label: 'Image conversion' },
        { value: 'other', label: 'Other' },
      ],
      order: 1,
    },
    {
      id: 'successRate',
      type: 'rating',
      text: 'How successful was the conversion?',
      required: true,
      validation: { max: 5 },
      order: 2,
    },
    {
      id: 'dataIntegrity',
      type: 'rating',
      text: 'How well was your data preserved during conversion?',
      required: true,
      validation: { max: 5 },
      order: 3,
    },
    {
      id: 'fileSize',
      type: 'choice',
      text: 'What was the approximate size of your file(s)?',
      options: [
        { value: 'small', label: 'Small (< 1MB)' },
        { value: 'medium', label: 'Medium (1MB - 10MB)' },
        { value: 'large', label: 'Large (10MB - 100MB)' },
        { value: 'very_large', label: 'Very large (> 100MB)' },
      ],
      required: false,
      order: 4,
    },
    {
      id: 'issues',
      type: 'multiple_choice',
      text: 'Did you encounter any issues? (Select all that apply)',
      options: [
        { value: 'data_loss', label: 'Data loss' },
        { value: 'formatting_issues', label: 'Formatting problems' },
        { value: 'encoding_problems', label: 'Character encoding issues' },
        { value: 'performance_slow', label: 'Slow performance' },
        { value: 'file_size_limit', label: 'File size limitations' },
        { value: 'no_issues', label: 'No issues' },
      ],
      required: false,
      order: 5,
    },
    {
      id: 'improvements',
      type: 'textarea',
      text: 'What would improve your file conversion experience?',
      required: false,
      validation: { maxLength: 500 },
      order: 6,
    },
  ],
  layout: {
    type: 'single_page',
    columns: 1,
    sections: [
      {
        id: 'conversion_info',
        title: 'Conversion Details',
        questions: ['conversionType', 'fileSize'],
        order: 1,
      },
      {
        id: 'quality_rating',
        title: 'Conversion Quality',
        questions: ['successRate', 'dataIntegrity'],
        order: 2,
      },
      {
        id: 'issues',
        title: 'Issues Encountered',
        questions: ['issues'],
        order: 3,
      },
      {
        id: 'feedback',
        title: 'Your Feedback',
        questions: ['improvements'],
        order: 4,
      },
    ],
    progressIndicator: true,
    navigation: {
      showPrevious: false,
      showNext: false,
      showSubmit: true,
      showCancel: true,
      submitLabel: 'Submit Feedback',
    },
  },
  styling: {
    theme: 'auto',
    colors: {
      primary: '#8B5CF6',
      secondary: '#6B7280',
      accent: '#10B981',
      background: '#FFFFFF',
      surface: '#F9FAFB',
      text: '#111827',
      error: '#EF4444',
      warning: '#F59E0B',
      success: '#10B981',
    },
    typography: {
      fontFamily: 'Inter, system-ui, sans-serif',
      fontSize: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
      },
      fontWeight: {
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
      },
      lineHeight: 1.5,
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '1rem',
      lg: '1.5rem',
      xl: '2rem',
      '2xl': '3rem',
    },
    animations: {
      duration: 200,
      easing: 'ease-in-out',
      enabled: true,
    },
  },
  localization: {
    title: 'File Conversion Experience',
    description: 'Tell us about your file conversion experience',
    questions: {
      conversionType: 'What type of conversion did you perform?',
      successRate: 'How successful was the conversion?',
      dataIntegrity: 'How well was your data preserved during conversion?',
      fileSize: 'What was the approximate size of your file(s)?',
      issues: 'Did you encounter any issues? (Select all that apply)',
      improvements: 'What would improve your file conversion experience?',
    },
    buttons: {
      previous: 'Previous',
      next: 'Next',
      submit: 'Submit Feedback',
      cancel: 'Cancel',
      skip: 'Skip',
    },
    validation: {
      required: 'This field is required',
      invalid: 'Please enter a valid value',
      minLength: 'Minimum length is {min} characters',
      maxLength: 'Maximum length is {max} characters',
    },
  },
};

// ============================================================================
// Security & Encryption Suite Templates
// ============================================================================

export const passwordGeneratorTemplate: FeedbackTemplate = {
  id: 'password-generator-feedback',
  name: 'Password Generator Feedback',
  type: 'satisfaction',
  title: 'Password Generator Experience',
  description: 'Help us improve our password generation tool',
  questions: [
    {
      id: 'securityRating',
      type: 'rating',
      text: 'How secure do you feel the generated passwords are?',
      required: true,
      validation: { max: 5 },
      order: 1,
    },
    {
      id: 'customizationSatisfaction',
      type: 'rating',
      text: 'How satisfied are you with the customization options?',
      required: true,
      validation: { max: 5 },
      order: 2,
    },
    {
      id: 'easeOfUse',
      type: 'rating',
      text: 'How easy was the tool to use?',
      required: true,
      validation: { max: 5 },
      order: 3,
    },
    {
      id: 'featuresUsed',
      type: 'multiple_choice',
      text: 'Which features did you use? (Select all that apply)',
      options: [
        { value: 'length_control', label: 'Password length control' },
        { value: 'character_types', label: 'Character type selection' },
        { value: 'exclude_similar', label: 'Exclude similar characters' },
        { value: 'exclude_ambiguous', label: 'Exclude ambiguous characters' },
        { value: 'pronounceable', label: 'Pronounceable passwords' },
        { value: 'passphrase', label: 'Passphrase generation' },
        { value: 'strength_indicator', label: 'Strength indicator' },
      ],
      required: false,
      order: 4,
    },
    {
      id: 'passwordUse',
      type: 'choice',
      text: 'What will you use these passwords for?',
      options: [
        { value: 'website_accounts', label: 'Website accounts' },
        { value: 'application_logins', label: 'Application logins' },
        { value: 'wifi_passwords', label: 'WiFi passwords' },
        { value: 'encryption_keys', label: 'Encryption keys' },
        { value: 'api_keys', label: 'API keys' },
        { value: 'other', label: 'Other security purposes' },
      ],
      required: false,
      order: 5,
    },
    {
      id: 'additionalFeatures',
      type: 'textarea',
      text: 'What additional features would you like to see in the password generator?',
      required: false,
      validation: { maxLength: 500 },
      order: 6,
    },
  ],
  layout: {
    type: 'single_page',
    columns: 1,
    sections: [
      {
        id: 'ratings',
        title: 'Rate Your Experience',
        questions: ['securityRating', 'customizationSatisfaction', 'easeOfUse'],
        order: 1,
      },
      {
        id: 'features',
        title: 'Features Used',
        questions: ['featuresUsed', 'passwordUse'],
        order: 2,
      },
      {
        id: 'suggestions',
        title: 'Feature Suggestions',
        questions: ['additionalFeatures'],
        order: 3,
      },
    ],
    progressIndicator: true,
    navigation: {
      showPrevious: false,
      showNext: false,
      showSubmit: true,
      showCancel: true,
      submitLabel: 'Submit Feedback',
    },
  },
  styling: {
    theme: 'auto',
    colors: {
      primary: '#10B981',
      secondary: '#6B7280',
      accent: '#3B82F6',
      background: '#FFFFFF',
      surface: '#F0FDF4',
      text: '#111827',
      error: '#EF4444',
      warning: '#F59E0B',
      success: '#10B981',
    },
    typography: {
      fontFamily: 'Inter, system-ui, sans-serif',
      fontSize: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
      },
      fontWeight: {
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
      },
      lineHeight: 1.5,
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '1rem',
      lg: '1.5rem',
      xl: '2rem',
      '2xl': '3rem',
    },
    animations: {
      duration: 200,
      easing: 'ease-in-out',
      enabled: true,
    },
  },
  localization: {
    title: 'Password Generator Experience',
    description: 'Help us improve our password generation tool',
    questions: {
      securityRating: 'How secure do you feel the generated passwords are?',
      customizationSatisfaction: 'How satisfied are you with the customization options?',
      easeOfUse: 'How easy was the tool to use?',
      featuresUsed: 'Which features did you use? (Select all that apply)',
      passwordUse: 'What will you use these passwords for?',
      additionalFeatures: 'What additional features would you like to see in the password generator?',
    },
    buttons: {
      previous: 'Previous',
      next: 'Next',
      submit: 'Submit Feedback',
      cancel: 'Cancel',
      skip: 'Skip',
    },
    validation: {
      required: 'This field is required',
      invalid: 'Please enter a valid value',
      minLength: 'Minimum length is {min} characters',
      maxLength: 'Maximum length is {max} characters',
    },
  },
};

// ============================================================================
// Text Processing Suite Templates
// ============================================================================

export const textEncoderTemplate: FeedbackTemplate = {
  id: 'text-encoder-feedback',
  name: 'Text Encoder Feedback',
  type: 'usability',
  title: 'Text Encoding/Decoding Experience',
  description: 'Tell us about your text encoding/decoding experience',
  questions: [
    {
      id: 'encodingType',
      type: 'choice',
      text: 'Which encoding type did you use?',
      required: true,
      options: [
        { value: 'base64', label: 'Base64' },
        { value: 'url_encoding', label: 'URL Encoding' },
        { value: 'html_entities', label: 'HTML Entities' },
        { value: 'unicode', label: 'Unicode' },
        { value: 'hexadecimal', label: 'Hexadecimal' },
        { value: 'binary', label: 'Binary' },
        { value: 'other', label: 'Other' },
      ],
      order: 1,
    },
    {
      id: 'accuracyRating',
      type: 'rating',
      text: 'How accurate was the encoding/decoding?',
      required: true,
      validation: { max: 5 },
      order: 2,
    },
    {
      id: 'easeOfUse',
      type: 'rating',
      text: 'How easy was the tool to use?',
      required: true,
      validation: { max: 5 },
      order: 3,
    },
    {
      id: 'performance',
      type: 'rating',
      text: 'How was the performance with your text size?',
      required: true,
      validation: { max: 5 },
      order: 4,
    },
    {
      id: 'textSize',
      type: 'choice',
      text: 'What was the approximate size of your text?',
      options: [
        { value: 'small', label: 'Small (< 1KB)' },
        { value: 'medium', label: 'Medium (1KB - 10KB)' },
        { value: 'large', label: 'Large (10KB - 100KB)' },
        { value: 'very_large', label: 'Very large (> 100KB)' },
      ],
      required: false,
      order: 5,
    },
    {
      id: 'issues',
      type: 'multiple_choice',
      text: 'Did you encounter any issues? (Select all that apply)',
      options: [
        { value: 'character_loss', label: 'Character loss or corruption' },
        { value: 'encoding_errors', label: 'Encoding errors' },
        { value: 'slow_performance', label: 'Slow performance' },
        { value: 'ui_issues', label: 'User interface issues' },
        { value: 'no_issues', label: 'No issues' },
      ],
      required: false,
      order: 6,
    },
  ],
  layout: {
    type: 'single_page',
    columns: 1,
    sections: [
      {
        id: 'encoding_info',
        title: 'Encoding Information',
        questions: ['encodingType', 'textSize'],
        order: 1,
      },
      {
        id: 'ratings',
        title: 'Rate Your Experience',
        questions: ['accuracyRating', 'easeOfUse', 'performance'],
        order: 2,
      },
      {
        id: 'issues',
        title: 'Issues Encountered',
        questions: ['issues'],
        order: 3,
      },
    ],
    progressIndicator: true,
    navigation: {
      showPrevious: false,
      showNext: false,
      showSubmit: true,
      showCancel: true,
      submitLabel: 'Submit Feedback',
    },
  },
  styling: {
    theme: 'auto',
    colors: {
      primary: '#F59E0B',
      secondary: '#6B7280',
      accent: '#3B82F6',
      background: '#FFFFFF',
      surface: '#FFFBEB',
      text: '#111827',
      error: '#EF4444',
      warning: '#F59E0B',
      success: '#10B981',
    },
    typography: {
      fontFamily: 'Inter, system-ui, sans-serif',
      fontSize: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
      },
      fontWeight: {
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
      },
      lineHeight: 1.5,
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '1rem',
      lg: '1.5rem',
      xl: '2rem',
      '2xl': '3rem',
    },
    animations: {
      duration: 200,
      easing: 'ease-in-out',
      enabled: true,
    },
  },
  localization: {
    title: 'Text Encoding/Decoding Experience',
    description: 'Tell us about your text encoding/decoding experience',
    questions: {
      encodingType: 'Which encoding type did you use?',
      accuracyRating: 'How accurate was the encoding/decoding?',
      easeOfUse: 'How easy was the tool to use?',
      performance: 'How was the performance with your text size?',
      textSize: 'What was the approximate size of your text?',
      issues: 'Did you encounter any issues? (Select all that apply)',
    },
    buttons: {
      previous: 'Previous',
      next: 'Next',
      submit: 'Submit Feedback',
      cancel: 'Cancel',
      skip: 'Skip',
    },
    validation: {
      required: 'This field is required',
      invalid: 'Please enter a valid value',
      minLength: 'Minimum length is {min} characters',
      maxLength: 'Maximum length is {max} characters',
    },
  },
};

// ============================================================================
// Network Utilities Templates
// ============================================================================

export const urlShortenerTemplate: FeedbackTemplate = {
  id: 'url-shortener-feedback',
  name: 'URL Shortener Feedback',
  type: 'satisfaction',
  title: 'URL Shortener Experience',
  description: 'Help us improve our URL shortening service',
  questions: [
    {
      id: 'reliabilityRating',
      type: 'rating',
      text: 'How reliable was the URL shortening service?',
      required: true,
      validation: { max: 5 },
      order: 1,
    },
    {
      id: 'easeOfUse',
      type: 'rating',
      text: 'How easy was the tool to use?',
      required: true,
      validation: { max: 5 },
      order: 2,
    },
    {
      id: 'customUrlRating',
      type: 'rating',
      text: 'How satisfied are you with the custom URL options?',
      required: false,
      validation: { max: 5 },
      order: 3,
    },
    {
      id: 'urlType',
      type: 'choice',
      text: 'What type of URLs did you shorten?',
      options: [
        { value: 'social_media', label: 'Social media links' },
        { value: 'marketing', label: 'Marketing campaigns' },
        { value: 'documentation', label: 'Documentation links' },
        { value: 'personal', label: 'Personal use' },
        { value: 'business', label: 'Business use' },
        { value: 'other', label: 'Other' },
      ],
      required: false,
      order: 4,
    },
    {
      id: 'featuresUsed',
      type: 'multiple_choice',
      text: 'Which features did you use? (Select all that apply)',
      options: [
        { value: 'basic_shortening', label: 'Basic URL shortening' },
        { value: 'custom_alias', label: 'Custom alias' },
        { value: 'qr_code', label: 'QR code generation' },
        { value: 'analytics', label: 'Link analytics' },
        { value: 'bulk_shortening', label: 'Bulk shortening' },
      ],
      required: false,
      order: 5,
    },
  ],
  layout: {
    type: 'single_page',
    columns: 1,
    sections: [
      {
        id: 'ratings',
        title: 'Rate Your Experience',
        questions: ['reliabilityRating', 'easeOfUse', 'customUrlRating'],
        order: 1,
      },
      {
        id: 'usage_info',
        title: 'Usage Information',
        questions: ['urlType', 'featuresUsed'],
        order: 2,
      },
    ],
    progressIndicator: true,
    navigation: {
      showPrevious: false,
      showNext: false,
      showSubmit: true,
      showCancel: true,
      submitLabel: 'Submit Feedback',
    },
  },
  styling: {
    theme: 'auto',
    colors: {
      primary: '#3B82F6',
      secondary: '#6B7280',
      accent: '#10B981',
      background: '#FFFFFF',
      surface: '#EFF6FF',
      text: '#111827',
      error: '#EF4444',
      warning: '#F59E0B',
      success: '#10B981',
    },
    typography: {
      fontFamily: 'Inter, system-ui, sans-serif',
      fontSize: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
      },
      fontWeight: {
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
      },
      lineHeight: 1.5,
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      md: '1rem',
      lg: '1.5rem',
      xl: '2rem',
      '2xl': '3rem',
    },
    animations: {
      duration: 200,
      easing: 'ease-in-out',
      enabled: true,
    },
  },
  localization: {
    title: 'URL Shortener Experience',
    description: 'Help us improve our URL shortening service',
    questions: {
      reliabilityRating: 'How reliable was the URL shortening service?',
      easeOfUse: 'How easy was the tool to use?',
      customUrlRating: 'How satisfied are you with the custom URL options?',
      urlType: 'What type of URLs did you shorten?',
      featuresUsed: 'Which features did you use? (Select all that apply)',
    },
    buttons: {
      previous: 'Previous',
      next: 'Next',
      submit: 'Submit Feedback',
      cancel: 'Cancel',
      skip: 'Skip',
    },
    validation: {
      required: 'This field is required',
      invalid: 'Please enter a valid value',
      minLength: 'Minimum length is {min} characters',
      maxLength: 'Maximum length is {max} characters',
    },
  },
};

// Export all templates
export const toolSpecificTemplates = {
  'json-formatter': jsonFormatterTemplate,
  'json-validator': jsonValidatorTemplate,
  'code-formatter': codeFormatterTemplate,
  'file-converter': fileConverterTemplate,
  'password-generator': passwordGeneratorTemplate,
  'text-encoder': textEncoderTemplate,
  'url-shortener': urlShortenerTemplate,
};

export default toolSpecificTemplates;
