name = "parsify-dev"
main = "src/worker.ts"
compatibility_date = "2026-05-19"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "c239b08869ed4cb6ad6bf46ad131f6eb"

[assets]
directory = "dist"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
