name = "parsify-dev"
main = "src/worker.ts"
compatibility_date = "2026-05-19"

[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiterDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RateLimiterDO"]

[assets]
binding = "ASSETS"
directory = "dist/client"
not_found_handling = "single-page-application"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
