apiVersion: apps/v1
kind: Deployment
metadata:
  name: parsify-api
  labels:
    app: parsify-api
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: parsify-api
  template:
    metadata:
      labels:
        app: parsify-api
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: parsify-api
        image: parsify/api:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: ENABLE_HEALTH_CHECKS
          value: "true"
        - name: ENABLE_METRICS
          value: "true"
        - name: LOG_LEVEL
          value: "info"
        - name: HEALTH_CHECK_AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: parsify-secrets
              key: health-check-auth-key
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: parsify-secrets
              key: jwt-secret
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: parsify-secrets
              key: sentry-dsn
        # Cloudflare bindings (in production, these would be configured differently)
        - name: CLOUDFLARE_ACCOUNT_ID
          valueFrom:
            secretKeyRef:
              name: parsify-secrets
              key: cloudflare-account-id
        # External service URLs for dependency health checks
        - name: EXTERNAL_API_URL
          value: "https://api.external-service.com"
        - name: PAYMENT_PROVIDER_URL
          value: "https://api.stripe.com"
        - name: NOTIFICATION_SERVICE_URL
          value: "https://api.twilio.com"

        # Health check configuration
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1

        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1

        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
          successThreshold: 1

        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true

      volumes:
      - name: config
        configMap:
          name: parsify-config

      # Security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000

      # Pod affinity and anti-affinity rules
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - parsify-api
              topologyKey: kubernetes.io/hostname

      # Node selector
      nodeSelector:
        kubernetes.io/os: linux

      # Toleration for dedicated nodes
      tolerations:
      - key: "dedicated"
        operator: "Equal"
        value: "parsify"
        effect: "NoExecute"
---
apiVersion: v1
kind: Service
metadata:
  name: parsify-api-service
  labels:
    app: parsify-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: parsify-api
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: parsify-api-monitor
  labels:
    app: parsify-api
spec:
  selector:
    matchLabels:
      app: parsify-api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: parsify-api-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: parsify-api
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: parsify-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: parsify-api
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: parsify-api-netpol
spec:
  podSelector:
    matchLabels:
      app: parsify-api
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8080
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: parsify-config
data:
  config.yaml: |
    health:
      checks:
        database:
          enabled: true
          interval: 30s
          timeout: 5s
          failureThreshold: 3
        cache:
          enabled: true
          interval: 60s
          timeout: 3s
        storage:
          enabled: true
          interval: 60s
          timeout: 10s
        external:
          - name: external-api
            url: https://api.external-service.com/health
            timeout: 5s
          - name: payment-provider
            url: https://api.stripe.com/v1
            timeout: 3s
    alerts:
      enabled: true
      channels:
        - type: email
          recipients:
            - ops@parsify.dev
        - type: slack
          webhook: https://hooks.slack.com/services/...
    metrics:
      enabled: true
      prometheus:
        enabled: true
        path: /metrics
---
# Gateway API configuration for advanced routing
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: parsify-api-route
  labels:
    app: parsify-api
spec:
  parentRefs:
  - name: parsify-gateway
    namespace: parsify
    sectionName: https
  hostnames:
  - "api.parsify.dev"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /health
    backendRefs:
    - name: parsify-api-service
      port: 80
    filters:
    - type: RequestHeaderModifier
      requestHeaderModifier:
        add:
        - name: X-Health-Check
          value: "true"
  - matches:
    - path:
        type: PathPrefix
        value: /api
    backendRefs:
    - name: parsify-api-service
      port: 80
    timeouts:
      request: 30s
  - matches:
    - path:
        type: Exact
        value: /
    backendRefs:
    - name: parsify-api-service
      port: 80
