name = "parsify-api"
main = "src/index-simple.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Workers specific configuration (no pages_build_output_dir)
[env.production.vars]
ENVIRONMENT = "production"
API_VERSION = "v1"
ENABLE_METRICS = "true"
LOG_LEVEL = "info"
ENABLE_HEALTH_CHECKS = "true"
ENABLE_CORS = "true"
MAX_REQUEST_SIZE = "10485760"
REQUEST_TIMEOUT = "30000"
DOMAIN = "parsify.dev"
JWT_SECRET = "production-jwt-secret-change-me-in-production"
SENTRY_DSN = "https://placeholder@o0.ingest.sentry.io/0"

[env.staging.vars]
ENVIRONMENT = "staging"
API_VERSION = "v1"
ENABLE_METRICS = "true"
LOG_LEVEL = "debug"
ENABLE_HEALTH_CHECKS = "true"
ENABLE_CORS = "true"
MAX_REQUEST_SIZE = "10485760"
REQUEST_TIMEOUT = "30000"
DOMAIN = "staging.parsify.dev"
JWT_SECRET = "staging-jwt-secret"
SENTRY_DSN = "https://placeholder@o0.ingest.sentry.io/0"

[env.development.vars]
ENVIRONMENT = "development"
API_VERSION = "v1"
ENABLE_METRICS = "true"
LOG_LEVEL = "debug"
ENABLE_HEALTH_CHECKS = "true"
ENABLE_CORS = "true"
MAX_REQUEST_SIZE = "10485760"
REQUEST_TIMEOUT = "30000"
DOMAIN = "localhost:8787"
JWT_SECRET = "development-jwt-secret"
SENTRY_DSN = ""

# D1 Database bindings
[[d1_databases]]
binding = "DB"
database_name = "parsify-prod"
database_id = "6378621c-903a-4ea7-911e-77195dcef14f"

# KV Namespace bindings
[[kv_namespaces]]
binding = "CACHE"
id = "31fb4cb2bd494a7789fecafd399912da"

[[kv_namespaces]]
binding = "SESSIONS"
id = "389e3a35ea3c431f89932c97ff8ada55"

[[kv_namespaces]]
binding = "UPLOADS"
id = "40f1ea2258a54d79948a44a186d89a01"

[[kv_namespaces]]
binding = "ANALYTICS"
id = "cf647eb2df824294aafb24daf084072e"

# R2 Bucket bindings
[[r2_buckets]]
binding = "FILES"
bucket_name = "parsify-prod-files"

# Custom domain routes for production
[[routes]]
pattern = "api.parsify.dev/*"
zone_name = "parsify.dev"

# Custom domain routes for staging
[[env.staging.routes]]
pattern = "api-staging.parsify.dev/*"
zone_name = "parsify.dev"
